mynodeapp:
    build: ./mynodeapp
    ports:
        - "8080:3000"
    volumes:
        - ./mynodeapp:/mynodeapp

webapp:
    build: ./webapp
    ports:
        - "1234:3000"
    volumes:
        - ./webapp:/webapp

data:
    build: ./data
    ports:
        - "27017:27017"
        - "28017:28017"
    volumes:
        - ./data:/data
